# Generated by Django 4.2.7 on 2026-01-26 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        ('organizations', '0001_initial'),
        ('users', '0002_student_gpa_student_updated_at_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorassignment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_assignments', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='supervisorassignment',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_assignment', to='users.student'),
        ),
        migrations.AddField(
            model_name='supervisorassignment',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_assignments', to='users.user'),
        ),
        migrations.AddField(
            model_name='application',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='organizations.internshippost'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'post')},
        ),
    ]
