# Generated by Django 5.2.10 on 2026-02-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_studenttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('declined', 'Declined')], default='pending', max_length=50),
        ),
    ]
