# Generated by Django 5.2.10 on 2026-02-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
