# Generated by Django 4.2.7 on 2026-01-26 19:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_student_gpa_student_updated_at_user_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='attendance_faces/')),
                ('face_confidence', models.FloatField(blank=True, null=True)),
                ('gps_latitude', models.FloatField(blank=True, null=True)),
                ('gps_longitude', models.FloatField(blank=True, null=True)),
                ('gps_accuracy', models.FloatField(blank=True, null=True)),
                ('verification_method', models.CharField(choices=[('face_gps', 'Face + GPS Verified'), ('manual', 'Manually Verified'), ('failed', 'Verification Failed')], max_length=50)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to='users.user')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.student')),
            ],
            options={
                'db_table': 'attendance',
                'unique_together': {('student', 'date')},
            },
        ),
    ]
