# Generated by Django 5.2.10 on 2026-02-10 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='face_confidence',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='face_image',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='gps_accuracy',
        ),
    ]
