# Generated by Django 4.2.7 on 2026-02-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_face_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('pending', 'Pending Verification')], max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='verification_method',
            field=models.CharField(choices=[('face_gps', 'Face + GPS Verified'), ('manual', 'Manually Verified'), ('failed', 'Verification Failed'), ('processing', 'AI Processing')], max_length=50),
        ),
    ]
